language: node_js
node_js:
    - "node"
    - "6"
notifications:
    webhooks:
        urls:
            - https://bot.proxy.bronies.link/travis/webhook/FVuAepmNLGP3Vso15hAYA49PkJrYdEjEwaGRYpQGS5E
        on_success: always
        on_failure: always
        on_start: never
